package irish.eimi.bratacha.common.datagen;

import irish.eimi.bratacha.BratachaMod;
import irish.eimi.bratacha.common.init.Registration;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class BratachaEnglishLanguage extends LanguageProvider {
    public BratachaEnglishLanguage(PackOutput output, String locale) {
        super(output, BratachaMod.MODID, locale);
    }

    @Override
    protected void addTranslations() {
        add("itemGroup.bratacha.country_flags","Country Flags");
        add(Registration.Countries.FLAG_BLOCK.get(),"Flag of Ireland");
        add(Registration.Countries.FLAG_COUNTRY_TOGO_BLOCK.get(),"Flag of Togo");
        add(Registration.Countries.FLAG_COUNTRY_MONTENEGRO_BLOCK.get(),"Flag of Montenegro");
        add(Registration.Countries.FLAG_COUNTRY_LAO_PEOPLES_DEMOCRATIC_REPUBLIC_BLOCK.get(),"Flag of Lao People's Democratic Republic");
        add(Registration.Countries.FLAG_COUNTRY_MAURITANIA_BLOCK.get(),"Flag of Mauritania");
        add(Registration.Countries.FLAG_COUNTRY_NICARAGUA_BLOCK.get(),"Flag of Nicaragua");
        add(Registration.Countries.FLAG_COUNTRY_LATVIA_BLOCK.get(),"Flag of Latvia");
        add(Registration.Countries.FLAG_COUNTRY_OMAN_BLOCK.get(),"Flag of Oman");
        add(Registration.Countries.FLAG_COUNTRY_AFGHANISTAN_BLOCK.get(),"Flag of Afghanistan");
        add(Registration.Countries.FLAG_COUNTRY_CYPRUS_BLOCK.get(),"Flag of Cyprus");
        add(Registration.Countries.FLAG_COUNTRY_BENIN_BLOCK.get(),"Flag of Benin");
        add(Registration.Countries.FLAG_COUNTRY_ANTARCTICA_BLOCK.get(),"Flag of Antarctica");
        add(Registration.Countries.FLAG_COUNTRY_CHINA_BLOCK.get(),"Flag of China");
        add(Registration.Countries.FLAG_COUNTRY_COLOMBIA_BLOCK.get(),"Flag of Colombia");
        add(Registration.Countries.FLAG_COUNTRY_CHRISTMAS_ISLAND_BLOCK.get(),"Flag of Christmas Island");
        add(Registration.Countries.FLAG_COUNTRY_ANTIGUA_AND_BARBUDA_BLOCK.get(),"Flag of Antigua and Barbuda");
        add(Registration.Countries.FLAG_COUNTRY_MONTSERRAT_BLOCK.get(),"Flag of Montserrat");
        add(Registration.Countries.FLAG_COUNTRY_MOLDOVA_REPUBLIC_OF_BLOCK.get(),"Flag of Moldova, Republic of");
        add(Registration.Countries.FLAG_COUNTRY_ZAMBIA_BLOCK.get(),"Flag of Zambia");
        add(Registration.Countries.FLAG_COUNTRY_VIET_NAM_BLOCK.get(),"Flag of Viet Nam");
        add(Registration.Countries.FLAG_COUNTRY_FRENCH_SOUTHERN_TERRITORIES_BLOCK.get(),"Flag of French Southern Territories");
        add(Registration.Countries.FLAG_COUNTRY_CHAD_BLOCK.get(),"Flag of Chad");
        add(Registration.Countries.FLAG_COUNTRY_MAYOTTE_BLOCK.get(),"Flag of Mayotte");
        add(Registration.Countries.FLAG_COUNTRY_LEBANON_BLOCK.get(),"Flag of Lebanon");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_MARTIN_FRENCH_PART_BLOCK.get(),"Flag of Saint Martin (French part)");
        add(Registration.Countries.FLAG_COUNTRY_LUXEMBOURG_BLOCK.get(),"Flag of Luxembourg");
        add(Registration.Countries.FLAG_COUNTRY_MARTINIQUE_BLOCK.get(),"Flag of Martinique");
        add(Registration.Countries.FLAG_COUNTRY_CZECHIA_BLOCK.get(),"Flag of Czechia");
        add(Registration.Countries.FLAG_COUNTRY_UNITED_ARAB_EMIRATES_BLOCK.get(),"Flag of United Arab Emirates");
        add(Registration.Countries.FLAG_COUNTRY_CAMEROON_BLOCK.get(),"Flag of Cameroon");
        add(Registration.Countries.FLAG_COUNTRY_BURUNDI_BLOCK.get(),"Flag of Burundi");
        add(Registration.Countries.FLAG_COUNTRY_ARGENTINA_BLOCK.get(),"Flag of Argentina");
        add(Registration.Countries.FLAG_COUNTRY_AMERICAN_SAMOA_BLOCK.get(),"Flag of American Samoa");
        add(Registration.Countries.FLAG_COUNTRY_BAHRAIN_BLOCK.get(),"Flag of Bahrain");
        add(Registration.Countries.FLAG_COUNTRY_CHILE_BLOCK.get(),"Flag of Chile");
        add(Registration.Countries.FLAG_COUNTRY_ANDORRA_BLOCK.get(),"Flag of Andorra");
        add(Registration.Countries.FLAG_COUNTRY_NORTHERN_MARIANA_ISLANDS_BLOCK.get(),"Flag of Northern Mariana Islands");
        add(Registration.Countries.FLAG_COUNTRY_LITHUANIA_BLOCK.get(),"Flag of Lithuania");
        add(Registration.Countries.FLAG_COUNTRY_MADAGASCAR_BLOCK.get(),"Flag of Madagascar");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_LUCIA_BLOCK.get(),"Flag of Saint Lucia");
        add(Registration.Countries.FLAG_COUNTRY_TRKIYE_BLOCK.get(),"Flag of Türkiye");
        add(Registration.Countries.FLAG_COUNTRY_UKRAINE_BLOCK.get(),"Flag of Ukraine");
        add(Registration.Countries.FLAG_COUNTRY_TUVALU_BLOCK.get(),"Flag of Tuvalu");
        add(Registration.Countries.FLAG_COUNTRY_VIRGIN_ISLANDS_US_BLOCK.get(),"Flag of Virgin Islands, U.S.");
        add(Registration.Countries.FLAG_COUNTRY_MALTA_BLOCK.get(),"Flag of Malta");
        add(Registration.Countries.FLAG_COUNTRY_NORWAY_BLOCK.get(),"Flag of Norway");
        add(Registration.Countries.FLAG_COUNTRY_MONACO_BLOCK.get(),"Flag of Monaco");
        add(Registration.Countries.FLAG_COUNTRY_SWITZERLAND_BLOCK.get(),"Flag of Switzerland");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_BARTHLEMY_BLOCK.get(),"Flag of Saint Barthélemy");
        add(Registration.Countries.FLAG_COUNTRY_ARUBA_BLOCK.get(),"Flag of Aruba");
        add(Registration.Countries.FLAG_COUNTRY_BELIZE_BLOCK.get(),"Flag of Belize");
        add(Registration.Countries.FLAG_COUNTRY_BERMUDA_BLOCK.get(),"Flag of Bermuda");
        add(Registration.Countries.FLAG_COUNTRY_CTE_DIVOIRE_BLOCK.get(),"Flag of Côte d'Ivoire");
        add(Registration.Countries.FLAG_COUNTRY_MAURITIUS_BLOCK.get(),"Flag of Mauritius");
        add(Registration.Countries.FLAG_COUNTRY_UNITED_STATES_OF_AMERICA_BLOCK.get(),"Flag of United States of America");
        add(Registration.Countries.FLAG_COUNTRY_TAIWAN_BLOCK.get(),"Flag of Taiwan");
        add(Registration.Countries.FLAG_COUNTRY_YEMEN_BLOCK.get(),"Flag of Yemen");
        add(Registration.Countries.FLAG_COUNTRY_MALAWI_BLOCK.get(),"Flag of Malawi");
        add(Registration.Countries.FLAG_COUNTRY_NETHERLANDS_BLOCK.get(),"Flag of Netherlands");
        add(Registration.Countries.FLAG_COUNTRY_LESOTHO_BLOCK.get(),"Flag of Lesotho");
        add(Registration.Countries.FLAG_COUNTRY_BOLIVIA_PLURINATIONAL_STATE_OF_BLOCK.get(),"Flag of Bolivia, Plurinational State of");
        add(Registration.Countries.FLAG_COUNTRY_AUSTRIA_BLOCK.get(),"Flag of Austria");
        add(Registration.Countries.FLAG_COUNTRY_COOK_ISLANDS_BLOCK.get(),"Flag of Cook Islands");
        add(Registration.Countries.FLAG_COUNTRY_BELARUS_BLOCK.get(),"Flag of Belarus");
        add(Registration.Countries.FLAG_COUNTRY_AUSTRALIA_BLOCK.get(),"Flag of Australia");
        add(Registration.Countries.FLAG_COUNTRY_BRUNEI_DARUSSALAM_BLOCK.get(),"Flag of Brunei Darussalam");
        add(Registration.Countries.FLAG_COUNTRY_MOROCCO_BLOCK.get(),"Flag of Morocco");
        add(Registration.Countries.FLAG_COUNTRY_NEW_ZEALAND_BLOCK.get(),"Flag of New Zealand");
        add(Registration.Countries.FLAG_COUNTRY_LIBERIA_BLOCK.get(),"Flag of Liberia");
        add(Registration.Countries.FLAG_COUNTRY_MALDIVES_BLOCK.get(),"Flag of Maldives");
        add(Registration.Countries.FLAG_COUNTRY_TURKS_AND_CAICOS_ISLANDS_BLOCK.get(),"Flag of Turks and Caicos Islands");
        add(Registration.Countries.FLAG_COUNTRY_UGANDA_BLOCK.get(),"Flag of Uganda");
        add(Registration.Countries.FLAG_COUNTRY_TRINIDAD_AND_TOBAGO_BLOCK.get(),"Flag of Trinidad and Tobago");
        add(Registration.Countries.FLAG_COUNTRY_POLAND_BLOCK.get(),"Flag of Poland");
        add(Registration.Countries.FLAG_COUNTRY_SERBIA_BLOCK.get(),"Flag of Serbia");
        add(Registration.Countries.FLAG_COUNTRY_INDIA_BLOCK.get(),"Flag of India");
        add(Registration.Countries.FLAG_COUNTRY_GEORGIA_BLOCK.get(),"Flag of Georgia");
        add(Registration.Countries.FLAG_COUNTRY_GREECE_BLOCK.get(),"Flag of Greece");
        add(Registration.Countries.FLAG_COUNTRY_SOUTH_GEORGIA_AND_THE_SOUTH_SANDWICH_ISLANDS_BLOCK.get(),"Flag of South Georgia and the South Sandwich Islands");
        add(Registration.Countries.FLAG_COUNTRY_GRENADA_BLOCK.get(),"Flag of Grenada");
        add(Registration.Countries.FLAG_COUNTRY_BRITISH_INDIAN_OCEAN_TERRITORY_BLOCK.get(),"Flag of British Indian Ocean Territory");
        add(Registration.Countries.FLAG_COUNTRY_HONG_KONG_BLOCK.get(),"Flag of Hong Kong");
        add(Registration.Countries.FLAG_COUNTRY_KOREA_DEMOCRATIC_PEOPLES_REPUBLIC_OF_BLOCK.get(),"Flag of Korea, Democratic People's Republic of");
        add(Registration.Countries.FLAG_COUNTRY_KYRGYZSTAN_BLOCK.get(),"Flag of Kyrgyzstan");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_PIERRE_AND_MIQUELON_BLOCK.get(),"Flag of Saint Pierre and Miquelon");
        add(Registration.Countries.FLAG_COUNTRY_EL_SALVADOR_BLOCK.get(),"Flag of El Salvador");
        add(Registration.Countries.FLAG_COUNTRY_RUNION_BLOCK.get(),"Flag of Réunion");
        add(Registration.Countries.FLAG_COUNTRY_SAUDI_ARABIA_BLOCK.get(),"Flag of Saudi Arabia");
        add(Registration.Countries.FLAG_COUNTRY_SEYCHELLES_BLOCK.get(),"Flag of Seychelles");
        add(Registration.Countries.FLAG_COUNTRY_SAO_TOME_AND_PRINCIPE_BLOCK.get(),"Flag of Sao Tome and Principe");
        add(Registration.Countries.FLAG_COUNTRY_KENYA_BLOCK.get(),"Flag of Kenya");
        add(Registration.Countries.FLAG_COUNTRY_ISLE_OF_MAN_BLOCK.get(),"Flag of Isle of Man");
        add(Registration.Countries.FLAG_COUNTRY_KOREA_REPUBLIC_OF_BLOCK.get(),"Flag of Korea, Republic of");
        add(Registration.Countries.FLAG_COUNTRY_FRENCH_GUIANA_BLOCK.get(),"Flag of French Guiana");
        add(Registration.Countries.FLAG_COUNTRY_DJIBOUTI_BLOCK.get(),"Flag of Djibouti");
        add(Registration.Countries.FLAG_COUNTRY_EQUATORIAL_GUINEA_BLOCK.get(),"Flag of Equatorial Guinea");
        add(Registration.Countries.FLAG_COUNTRY_GUADELOUPE_BLOCK.get(),"Flag of Guadeloupe");
        add(Registration.Countries.FLAG_COUNTRY_DENMARK_BLOCK.get(),"Flag of Denmark");
        add(Registration.Countries.FLAG_COUNTRY_GUERNSEY_BLOCK.get(),"Flag of Guernsey");
        add(Registration.Countries.FLAG_COUNTRY_ISRAEL_BLOCK.get(),"Flag of Israel");
        add(Registration.Countries.FLAG_COUNTRY_PITCAIRN_BLOCK.get(),"Flag of Pitcairn");
        add(Registration.Countries.FLAG_COUNTRY_SOLOMON_ISLANDS_BLOCK.get(),"Flag of Solomon Islands");
        add(Registration.Countries.FLAG_COUNTRY_PARAGUAY_BLOCK.get(),"Flag of Paraguay");
        add(Registration.Countries.FLAG_COUNTRY_RUSSIAN_FEDERATION_BLOCK.get(),"Flag of Russian Federation");
        add(Registration.Countries.FLAG_COUNTRY_KUWAIT_BLOCK.get(),"Flag of Kuwait");
        add(Registration.Countries.FLAG_COUNTRY_DOMINICAN_REPUBLIC_BLOCK.get(),"Flag of Dominican Republic");
        add(Registration.Countries.FLAG_COUNTRY_GUATEMALA_BLOCK.get(),"Flag of Guatemala");
        add(Registration.Countries.FLAG_COUNTRY_UNITED_KINGDOM_OF_GREAT_BRITAIN_AND_NORTHERN_IRELAND_BLOCK.get(),"Flag of United Kingdom of Great Britain and Northern Ireland");
        add(Registration.Countries.FLAG_COUNTRY_GUAM_BLOCK.get(),"Flag of Guam");
        add(Registration.Countries.FLAG_COUNTRY_JERSEY_BLOCK.get(),"Flag of Jersey");
        add(Registration.Countries.FLAG_COUNTRY_HEARD_ISLAND_AND_MCDONALD_ISLANDS_BLOCK.get(),"Flag of Heard Island and McDonald Islands");
        add(Registration.Countries.FLAG_COUNTRY_SINGAPORE_BLOCK.get(),"Flag of Singapore");
        add(Registration.Countries.FLAG_COUNTRY_PAKISTAN_BLOCK.get(),"Flag of Pakistan");
        add(Registration.Countries.FLAG_COUNTRY_SURINAME_BLOCK.get(),"Flag of Suriname");
        add(Registration.Countries.FLAG_COUNTRY_SWEDEN_BLOCK.get(),"Flag of Sweden");
        add(Registration.Countries.FLAG_COUNTRY_JAPAN_BLOCK.get(),"Flag of Japan");
        add(Registration.Countries.FLAG_COUNTRY_GUINEABISSAU_BLOCK.get(),"Flag of Guinea-Bissau");
        add(Registration.Countries.FLAG_COUNTRY_WESTERN_SAHARA_BLOCK.get(),"Flag of Western Sahara");
        add(Registration.Countries.FLAG_COUNTRY_ALGERIA_BLOCK.get(),"Flag of Algeria");
        add(Registration.Countries.FLAG_COUNTRY_GABON_BLOCK.get(),"Flag of Gabon");
        add(Registration.Countries.FLAG_COUNTRY_FRANCE_BLOCK.get(),"Flag of France");
        add(Registration.Countries.FLAG_COUNTRY_DOMINICA_BLOCK.get(),"Flag of Dominica");
        add(Registration.Countries.FLAG_COUNTRY_HONDURAS_BLOCK.get(),"Flag of Honduras");
        add(Registration.Countries.FLAG_COUNTRY_SUDAN_BLOCK.get(),"Flag of Sudan");
        add(Registration.Countries.FLAG_COUNTRY_RWANDA_BLOCK.get(),"Flag of Rwanda");
        add(Registration.Countries.FLAG_COUNTRY_PHILIPPINES_BLOCK.get(),"Flag of Philippines");
        add(Registration.Countries.FLAG_COUNTRY_SOUTH_SUDAN_BLOCK.get(),"Flag of South Sudan");
        add(Registration.Countries.FLAG_COUNTRY_QATAR_BLOCK.get(),"Flag of Qatar");
        add(Registration.Countries.FLAG_COUNTRY_PERU_BLOCK.get(),"Flag of Peru");
        add(Registration.Countries.FLAG_COUNTRY_PUERTO_RICO_BLOCK.get(),"Flag of Puerto Rico");
        add(Registration.Countries.FLAG_COUNTRY_SLOVENIA_BLOCK.get(),"Flag of Slovenia");
        add(Registration.Countries.FLAG_COUNTRY_HAITI_BLOCK.get(),"Flag of Haiti");
        add(Registration.Countries.FLAG_COUNTRY_SPAIN_BLOCK.get(),"Flag of Spain");
        add(Registration.Countries.FLAG_COUNTRY_GREENLAND_BLOCK.get(),"Flag of Greenland");
        add(Registration.Countries.FLAG_COUNTRY_GAMBIA_BLOCK.get(),"Flag of Gambia");
        add(Registration.Countries.FLAG_COUNTRY_ERITREA_BLOCK.get(),"Flag of Eritrea");
        add(Registration.Countries.FLAG_COUNTRY_FINLAND_BLOCK.get(),"Flag of Finland");
        add(Registration.Countries.FLAG_COUNTRY_ESTONIA_BLOCK.get(),"Flag of Estonia");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_KITTS_AND_NEVIS_BLOCK.get(),"Flag of Saint Kitts and Nevis");
        add(Registration.Countries.FLAG_COUNTRY_HUNGARY_BLOCK.get(),"Flag of Hungary");
        add(Registration.Countries.FLAG_COUNTRY_IRAQ_BLOCK.get(),"Flag of Iraq");
        add(Registration.Countries.FLAG_COUNTRY_CAYMAN_ISLANDS_BLOCK.get(),"Flag of Cayman Islands");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_HELENA_ASCENSION_AND_TRISTAN_DA_CUNHA_BLOCK.get(),"Flag of Saint Helena, Ascension and Tristan da Cunha");
        add(Registration.Countries.FLAG_COUNTRY_PALESTINE_BLOCK.get(),"Flag of Palestine");
        add(Registration.Countries.FLAG_COUNTRY_FRENCH_POLYNESIA_BLOCK.get(),"Flag of French Polynesia");
        add(Registration.Countries.FLAG_COUNTRY_SVALBARD_AND_JAN_MAYEN_BLOCK.get(),"Flag of Svalbard and Jan Mayen");
        add(Registration.Countries.FLAG_COUNTRY_INDONESIA_BLOCK.get(),"Flag of Indonesia");
        add(Registration.Countries.FLAG_COUNTRY_ICELAND_BLOCK.get(),"Flag of Iceland");
        add(Registration.Countries.FLAG_COUNTRY_EGYPT_BLOCK.get(),"Flag of Egypt");
        add(Registration.Countries.FLAG_COUNTRY_FALKLAND_ISLANDS_MALVINAS_BLOCK.get(),"Flag of Falkland Islands (Malvinas)");
        add(Registration.Countries.FLAG_COUNTRY_FIJI_BLOCK.get(),"Flag of Fiji");
        add(Registration.Countries.FLAG_COUNTRY_GUINEA_BLOCK.get(),"Flag of Guinea");
        add(Registration.Countries.FLAG_COUNTRY_GUYANA_BLOCK.get(),"Flag of Guyana");
        add(Registration.Countries.FLAG_COUNTRY_IRAN_ISLAMIC_REPUBLIC_OF_BLOCK.get(),"Flag of Iran, Islamic Republic of");
        add(Registration.Countries.FLAG_COUNTRY_COMOROS_BLOCK.get(),"Flag of Comoros");
        add(Registration.Countries.FLAG_COUNTRY_IRELAND_BLOCK.get(),"Flag of Ireland");
        add(Registration.Countries.FLAG_COUNTRY_KAZAKHSTAN_BLOCK.get(),"Flag of Kazakhstan");
        add(Registration.Countries.FLAG_COUNTRY_ROMANIA_BLOCK.get(),"Flag of Romania");
        add(Registration.Countries.FLAG_COUNTRY_SLOVAKIA_BLOCK.get(),"Flag of Slovakia");
        add(Registration.Countries.FLAG_COUNTRY_PAPUA_NEW_GUINEA_BLOCK.get(),"Flag of Papua New Guinea");
        add(Registration.Countries.FLAG_COUNTRY_PORTUGAL_BLOCK.get(),"Flag of Portugal");
        add(Registration.Countries.FLAG_COUNTRY_SOMALIA_BLOCK.get(),"Flag of Somalia");
        add(Registration.Countries.FLAG_COUNTRY_SINT_MAARTEN_DUTCH_PART_BLOCK.get(),"Flag of Sint Maarten (Dutch part)");
        add(Registration.Countries.FLAG_COUNTRY_CROATIA_BLOCK.get(),"Flag of Croatia");
        add(Registration.Countries.FLAG_COUNTRY_KIRIBATI_BLOCK.get(),"Flag of Kiribati");
        add(Registration.Countries.FLAG_COUNTRY_JAMAICA_BLOCK.get(),"Flag of Jamaica");
        add(Registration.Countries.FLAG_COUNTRY_ECUADOR_BLOCK.get(),"Flag of Ecuador");
        add(Registration.Countries.FLAG_COUNTRY_ETHIOPIA_BLOCK.get(),"Flag of Ethiopia");
        add(Registration.Countries.FLAG_COUNTRY_FAROE_ISLANDS_BLOCK.get(),"Flag of Faroe Islands");
        add(Registration.Countries.FLAG_COUNTRY_CAMBODIA_BLOCK.get(),"Flag of Cambodia");
        add(Registration.Countries.FLAG_COUNTRY_SYRIAN_ARAB_REPUBLIC_BLOCK.get(),"Flag of Syrian Arab Republic");
        add(Registration.Countries.FLAG_COUNTRY_SENEGAL_BLOCK.get(),"Flag of Senegal");
        add(Registration.Countries.FLAG_COUNTRY_PALAU_BLOCK.get(),"Flag of Palau");
        add(Registration.Countries.FLAG_COUNTRY_SIERRA_LEONE_BLOCK.get(),"Flag of Sierra Leone");
        add(Registration.Countries.FLAG_COUNTRY_MICRONESIA_FEDERATED_STATES_OF_BLOCK.get(),"Flag of Micronesia, Federated States of");
        add(Registration.Countries.FLAG_COUNTRY_GIBRALTAR_BLOCK.get(),"Flag of Gibraltar");
        add(Registration.Countries.FLAG_COUNTRY_GERMANY_BLOCK.get(),"Flag of Germany");
        add(Registration.Countries.FLAG_COUNTRY_GHANA_BLOCK.get(),"Flag of Ghana");
        add(Registration.Countries.FLAG_COUNTRY_JORDAN_BLOCK.get(),"Flag of Jordan");
        add(Registration.Countries.FLAG_COUNTRY_ITALY_BLOCK.get(),"Flag of Italy");
        add(Registration.Countries.FLAG_COUNTRY_PANAMA_BLOCK.get(),"Flag of Panama");
        add(Registration.Countries.FLAG_COUNTRY_ESWATINI_BLOCK.get(),"Flag of Eswatini");
        add(Registration.Countries.FLAG_COUNTRY_SAN_MARINO_BLOCK.get(),"Flag of San Marino");
        add(Registration.Countries.FLAG_COUNTRY_TUNISIA_BLOCK.get(),"Flag of Tunisia");
        add(Registration.Countries.FLAG_COUNTRY_MALI_BLOCK.get(),"Flag of Mali");
        add(Registration.Countries.FLAG_COUNTRY_CONGO_BLOCK.get(),"Flag of Congo");
        add(Registration.Countries.FLAG_COUNTRY_LAND_ISLANDS_BLOCK.get(),"Flag of Åland Islands");
        add(Registration.Countries.FLAG_COUNTRY_ANGOLA_BLOCK.get(),"Flag of Angola");
        add(Registration.Countries.FLAG_COUNTRY_BHUTAN_BLOCK.get(),"Flag of Bhutan");
        add(Registration.Countries.FLAG_COUNTRY_BARBADOS_BLOCK.get(),"Flag of Barbados");
        add(Registration.Countries.FLAG_COUNTRY_CENTRAL_AFRICAN_REPUBLIC_BLOCK.get(),"Flag of Central African Republic");
        add(Registration.Countries.FLAG_COUNTRY_MYANMAR_BLOCK.get(),"Flag of Myanmar");
        add(Registration.Countries.FLAG_COUNTRY_LIECHTENSTEIN_BLOCK.get(),"Flag of Liechtenstein");
        add(Registration.Countries.FLAG_COUNTRY_NAMIBIA_BLOCK.get(),"Flag of Namibia");
        add(Registration.Countries.FLAG_COUNTRY_MOZAMBIQUE_BLOCK.get(),"Flag of Mozambique");
        add(Registration.Countries.FLAG_COUNTRY_TONGA_BLOCK.get(),"Flag of Tonga");
        add(Registration.Countries.FLAG_COUNTRY_VIRGIN_ISLANDS_BRITISH_BLOCK.get(),"Flag of Virgin Islands, British");
        add(Registration.Countries.FLAG_COUNTRY_VENEZUELA_BOLIVARIAN_REPUBLIC_OF_BLOCK.get(),"Flag of Venezuela, Bolivarian Republic of");
        add(Registration.Countries.FLAG_COUNTRY_TANZANIA_UNITED_REPUBLIC_OF_BLOCK.get(),"Flag of Tanzania, United Republic of");
        add(Registration.Countries.FLAG_COUNTRY_TURKMENISTAN_BLOCK.get(),"Flag of Turkmenistan");
        add(Registration.Countries.FLAG_COUNTRY_MEXICO_BLOCK.get(),"Flag of Mexico");
        add(Registration.Countries.FLAG_COUNTRY_NEW_CALEDONIA_BLOCK.get(),"Flag of New Caledonia");
        add(Registration.Countries.FLAG_COUNTRY_MACAO_BLOCK.get(),"Flag of Macao");
        add(Registration.Countries.FLAG_COUNTRY_SRI_LANKA_BLOCK.get(),"Flag of Sri Lanka");
        add(Registration.Countries.FLAG_COUNTRY_CONGO_DEMOCRATIC_REPUBLIC_OF_THE_BLOCK.get(),"Flag of Congo, Democratic Republic of the");
        add(Registration.Countries.FLAG_COUNTRY_ALBANIA_BLOCK.get(),"Flag of Albania");
        add(Registration.Countries.FLAG_COUNTRY_BOTSWANA_BLOCK.get(),"Flag of Botswana");
        add(Registration.Countries.FLAG_COUNTRY_COSTA_RICA_BLOCK.get(),"Flag of Costa Rica");
        add(Registration.Countries.FLAG_COUNTRY_BOUVET_ISLAND_BLOCK.get(),"Flag of Bouvet Island");
        add(Registration.Countries.FLAG_COUNTRY_ARMENIA_BLOCK.get(),"Flag of Armenia");
        add(Registration.Countries.FLAG_COUNTRY_AZERBAIJAN_BLOCK.get(),"Flag of Azerbaijan");
        add(Registration.Countries.FLAG_COUNTRY_BOSNIA_AND_HERZEGOVINA_BLOCK.get(),"Flag of Bosnia and Herzegovina");
        add(Registration.Countries.FLAG_COUNTRY_MONGOLIA_BLOCK.get(),"Flag of Mongolia");
        add(Registration.Countries.FLAG_COUNTRY_NIUE_BLOCK.get(),"Flag of Niue");
        add(Registration.Countries.FLAG_COUNTRY_MALAYSIA_BLOCK.get(),"Flag of Malaysia");
        add(Registration.Countries.FLAG_COUNTRY_TIMORLESTE_BLOCK.get(),"Flag of Timor-Leste");
        add(Registration.Countries.FLAG_COUNTRY_SAMOA_BLOCK.get(),"Flag of Samoa");
        add(Registration.Countries.FLAG_COUNTRY_THAILAND_BLOCK.get(),"Flag of Thailand");
        add(Registration.Countries.FLAG_COUNTRY_KOSOVO_BLOCK.get(),"Flag of Kosovo");
        add(Registration.Countries.FLAG_COUNTRY_NORFOLK_ISLAND_BLOCK.get(),"Flag of Norfolk Island");
        add(Registration.Countries.FLAG_COUNTRY_LIBYA_BLOCK.get(),"Flag of Libya");
        add(Registration.Countries.FLAG_COUNTRY_ANGUILLA_BLOCK.get(),"Flag of Anguilla");
        add(Registration.Countries.FLAG_COUNTRY_BRAZIL_BLOCK.get(),"Flag of Brazil");
        add(Registration.Countries.FLAG_COUNTRY_CABO_VERDE_BLOCK.get(),"Flag of Cabo Verde");
        add(Registration.Countries.FLAG_COUNTRY_BELGIUM_BLOCK.get(),"Flag of Belgium");
        add(Registration.Countries.FLAG_COUNTRY_CANADA_BLOCK.get(),"Flag of Canada");
        add(Registration.Countries.FLAG_COUNTRY_BANGLADESH_BLOCK.get(),"Flag of Bangladesh");
        add(Registration.Countries.FLAG_COUNTRY_CURAAO_BLOCK.get(),"Flag of Curaçao");
        add(Registration.Countries.FLAG_COUNTRY_BAHAMAS_BLOCK.get(),"Flag of Bahamas");
        add(Registration.Countries.FLAG_COUNTRY_NIGERIA_BLOCK.get(),"Flag of Nigeria");
        add(Registration.Countries.FLAG_COUNTRY_NORTH_MACEDONIA_BLOCK.get(),"Flag of North Macedonia");
        add(Registration.Countries.FLAG_COUNTRY_NEPAL_BLOCK.get(),"Flag of Nepal");
        add(Registration.Countries.FLAG_COUNTRY_HOLY_SEE_BLOCK.get(),"Flag of Holy See");
        add(Registration.Countries.FLAG_COUNTRY_UZBEKISTAN_BLOCK.get(),"Flag of Uzbekistan");
        add(Registration.Countries.FLAG_COUNTRY_UNITED_STATES_MINOR_OUTLYING_ISLANDS_BLOCK.get(),"Flag of United States Minor Outlying Islands");
        add(Registration.Countries.FLAG_COUNTRY_TOKELAU_BLOCK.get(),"Flag of Tokelau");
        add(Registration.Countries.FLAG_COUNTRY_SAINT_VINCENT_AND_THE_GRENADINES_BLOCK.get(),"Flag of Saint Vincent and the Grenadines");
        add(Registration.Countries.FLAG_COUNTRY_ZIMBABWE_BLOCK.get(),"Flag of Zimbabwe");
        add(Registration.Countries.FLAG_COUNTRY_NAURU_BLOCK.get(),"Flag of Nauru");
        add(Registration.Countries.FLAG_COUNTRY_NIGER_BLOCK.get(),"Flag of Niger");
        add(Registration.Countries.FLAG_COUNTRY_CUBA_BLOCK.get(),"Flag of Cuba");
        add(Registration.Countries.FLAG_COUNTRY_BONAIRE_SINT_EUSTATIUS_AND_SABA_BLOCK.get(),"Flag of Bonaire, Sint Eustatius and Saba");
        add(Registration.Countries.FLAG_COUNTRY_BURKINA_FASO_BLOCK.get(),"Flag of Burkina Faso");
        add(Registration.Countries.FLAG_COUNTRY_BULGARIA_BLOCK.get(),"Flag of Bulgaria");
        add(Registration.Countries.FLAG_COUNTRY_COCOS_KEELING_ISLANDS_BLOCK.get(),"Flag of Cocos (Keeling) Islands");
        add(Registration.Countries.FLAG_COUNTRY_MARSHALL_ISLANDS_BLOCK.get(),"Flag of Marshall Islands");
        add(Registration.Countries.FLAG_COUNTRY_SOUTH_AFRICA_BLOCK.get(),"Flag of South Africa");
        add(Registration.Countries.FLAG_COUNTRY_URUGUAY_BLOCK.get(),"Flag of Uruguay");
        add(Registration.Countries.FLAG_COUNTRY_WALLIS_AND_FUTUNA_BLOCK.get(),"Flag of Wallis and Futuna");
        add(Registration.Countries.FLAG_COUNTRY_VANUATU_BLOCK.get(),"Flag of Vanuatu");
        add(Registration.Countries.FLAG_COUNTRY_TAJIKISTAN_BLOCK.get(),"Flag of Tajikistan");
    }
}
